"""Response critic implementation for M12 Self-Reflection & Self-Correction.

Evaluates claims against their verification results to produce actionable,
claim-targeted critiques for the rewriter.

Reliability Invariant:
    * Does NOT independently perform verification; consumes M07 VerificationResult.
    * Claim-targeted: isolates contradicted and unsupported claims rather than
      relying on generic rewriting.
    * No evidence remains UNKNOWN, never SUPPORTED.
"""

from __future__ import annotations

from eclair.contracts.claim import Claim
from eclair.contracts.enums import VerificationStatus
from eclair.contracts.evidence import Evidence
from eclair.contracts.verification import VerificationResult
from eclair.reflection.models import CritiqueItem, CritiqueReport

__all__ = ["ResponseCritic"]


class ResponseCritic:
    """Critic that analyzes verification results to generate targeted correction directives."""

    def critique(
        self,
        claims: list[Claim],
        verifications: list[VerificationResult],
        evidence: list[Evidence] | None = None,
    ) -> CritiqueReport:
        """Analyze verified claims and generate a structured CritiqueReport.

        Args:
            claims: The extracted claims to critique.
            verifications: M07 verification results for the claims.
            evidence: Optional supporting evidence passages.

        Returns:
            A structured CritiqueReport detailing failing claims and recommendations.
        """
        verif_map: dict[str, VerificationResult] = {v.claim_id: v for v in verifications}
        items: list[CritiqueItem] = []

        for claim in claims:
            verif = verif_map.get(claim.claim_id)
            if verif is None:
                # If a claim was not verified, treat as UNKNOWN (unverified)
                items.append(
                    CritiqueItem(
                        claim_id=claim.claim_id,
                        claim_text=claim.text,
                        verification_status=VerificationStatus.UNKNOWN,
                        issue="Claim was not verified against evidence.",
                        recommendation="Verify against knowledge base or remove if unverified.",
                    )
                )
                continue

            if verif.status == VerificationStatus.CONTRADICTED:
                items.append(
                    CritiqueItem(
                        claim_id=claim.claim_id,
                        claim_text=claim.text,
                        verification_status=VerificationStatus.CONTRADICTED,
                        issue="Claim is explicitly contradicted by retrieved evidence.",
                        recommendation="Remove or invert statement to align strictly with factual evidence.",
                    )
                )
            elif verif.status == VerificationStatus.UNKNOWN:
                items.append(
                    CritiqueItem(
                        claim_id=claim.claim_id,
                        claim_text=claim.text,
                        verification_status=VerificationStatus.UNKNOWN,
                        issue="Claim lacks supporting evidence (ungrounded assertion).",
                        recommendation="Ground with verified knowledge base facts or omit unsupported details.",
                    )
                )

        weak_count = len(items)
        has_weak = weak_count > 0

        if not has_weak:
            summary = "All claims are supported by verified evidence. No corrective critique required."
        else:
            contradicted_count = sum(
                1 for i in items if i.verification_status == VerificationStatus.CONTRADICTED
            )
            unknown_count = sum(
                1 for i in items if i.verification_status == VerificationStatus.UNKNOWN
            )
            summary = (
                f"Identified {weak_count} weak claim(s): {contradicted_count} contradicted, "
                f"{unknown_count} unsupported. Correct or omit these specific claims."
            )

        return CritiqueReport(
            has_weak_claims=has_weak,
            weak_claim_count=weak_count,
            items=items,
            summary=summary,
        )

    def format_critique_for_prompt(
        self,
        critique: CritiqueReport,
        evidence: list[Evidence] | None = None,
    ) -> str:
        """Format the critique and evidence into a clear instruction block for the LLM rewriter.

        Args:
            critique: The critique report generated by critique().
            evidence: Supporting evidence passages.

        Returns:
            A formatted prompt section guiding targeted revision.
        """
        lines: list[str] = ["CRITIQUE OF CURRENT ANSWER:"]
        if not critique.has_weak_claims:
            lines.append("No specific weaknesses detected.")
            return "\n".join(lines)

        lines.append(f"Summary: {critique.summary}")
        lines.append("\nSPECIFIC CLAIMS TO CORRECT OR OMIT:")
        for idx, item in enumerate(critique.items, start=1):
            status_name = item.verification_status.value
            lines.append(f"{idx}. Claim: \"{item.claim_text}\"")
            lines.append(f"   Status: {status_name}")
            lines.append(f"   Issue: {item.issue}")
            lines.append(f"   Correction Directive: {item.recommendation}")

        if evidence:
            lines.append("\nAVAILABLE FACTUAL EVIDENCE TO GROUND THE REVISION:")
            for e_idx, ev in enumerate(evidence, start=1):
                src = f" (Source: {ev.source})" if ev.source else ""
                lines.append(f"[{e_idx}]{src}: {ev.text}")

        return "\n".join(lines)
